site_name: Cloud Science Platforms
repo_url: https://github.com/stackhpc/azimuth-user-docs
copyright: |
  Copyright &copy; 2016-2022 StackHPC
theme:
  features:
    - navigation.tracking
  name: material
  icon:
    logo: material/lightbulb-on
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue grey
      accent: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: deep purple
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
